# -*- coding: utf-8 -*-
"""
Author: Manoj Mishra
"""

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from reportlab.platypus import Image
from io import BytesIO

def generate_stage_chart(report):

    labels = list(
        report["stage_summary"].keys()
    )

    values = list(
        report["stage_summary"].values()
    )

    fig, ax = plt.subplots(

        figsize=(8, 4),

        dpi=300
    )

    bars = ax.barh(

        labels,

        values
    )

    # VALUE LABELS

    for bar in bars:

        width = bar.get_width()

        ax.text(

            width + 0.3,

            bar.get_y() + bar.get_height()/2,

            str(int(width)),

            va="center",

            fontsize=10
        )

    ax.set_title(

        "Deployment Stage Distribution",

        fontsize=14,

        fontweight="bold"
    )

    ax.set_xlabel("Node Count")

    ax.grid(

        axis="x",

        linestyle="--",

        alpha=0.4
    )

    plt.tight_layout()

    image_buffer = BytesIO()

    plt.savefig(

        image_buffer,

        format="png",

        dpi=300,

        bbox_inches="tight",

        facecolor="white"
    )

    plt.close(fig)

    image_buffer.seek(0)

    return image_buffer


def add_page_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        9
    )

    canvas.drawString(

        30,

        20,

        "Integrated Project Tracking Tool (IPTT)"
    )

    canvas.drawRightString(

        580,

        20,

        f"Page {doc.page}"
    )

    canvas.restoreState()

def section_header(text, styles):

    return Paragraph(

        f"""
        <font size=15>
        <b>{text}</b>
        </font>
        """,

        styles["Heading2"]
    )

def generate_executive_pdf(
    project,
    report
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=20
    )

    styles = getSampleStyleSheet()
    
    # =====================================
    # SECTION TITLE STYLE
    # =====================================
    
    section_style = styles["Heading2"]

    elements = []
    
    # =====================================
    # COVER PAGE
    # =====================================
    
    cover = Paragraph(
    
        f"""
        <font size=24>
        <b>Executive Project Report</b>
        </font>
    
        <br/><br/>
    
        <font size=18>
        {project.name}
        </font>
    
        <br/><br/><br/>
    
        Generated by IPTT
        """,
    
        styles["Title"]
    )
    
    elements.append(Spacer(1, 180))
    
    elements.append(cover)
    
    elements.append(PageBreak())

    # =====================================
    # TITLE
    # =====================================

    title = Paragraph(

        f"""
        <b>Executive Dashboard Report</b><br/>
        Project: {project.name}
        """,

        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # =====================================
    # EXECUTIVE SUMMARY
    # =====================================

    summary = Paragraph(

        report["executive_summary"],

        styles["BodyText"]
    )

    elements.append(summary)

    elements.append(Spacer(1, 20))

          
    # =====================================
    # KPI TABLE
    # =====================================

    kpi_data = [

        ["KPI", "Value"],

        ["Progress", f"{report['kpis']['progress']}%"],

        ["Health", f"{report['kpis']['health']}%"],

        ["Status", report['kpis']['status']],

        ["Delayed Items", str(report['delayed_count'])],

        ["Bottleneck", report['bottleneck']]
    ]

    table = Table(
        kpi_data,
        repeatRows=1,
        colWidths=[220, 220]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2933")),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))

    elements.append(table)

    elements.append(Spacer(1, 25))

    
    # =====================================
    # STAGE CHART
    # =====================================
    
    chart_buffer = generate_stage_chart(report)
    
    chart = Image(
    
        chart_buffer,
    
        width=500,
    
        height=260
    )
    
    elements.append(chart)
    
    elements.append(Spacer(1, 20))
    elements.append(PageBreak())
    # =====================================
    # STAGE AGING
    # =====================================
    
    aging_title = Paragraph(
    
        "Stage Aging Analysis",
    
        section_style
    )
    
    elements.append(aging_title)
    
    elements.append(Spacer(1, 10))
    
    aging_data = [[
    
        "Stage",
        "Nodes",
        "Avg Delay",
        "Max Delay",
        "Risk"
    ]]
    
    for item in report["stage_aging"]:
    
        aging_data.append([
    
            item["stage"],
    
            str(item["nodes"]),
    
            f"{item['avg_delay']} days",
    
            f"{item['max_delay']} days",
    
            item["risk"]
        ])
    
    aging_table = Table(
    
        aging_data,
        
        repeatRows=1,
    
        colWidths=[140, 70, 100, 100, 100]
        
    )
    
    aging_table.setStyle(TableStyle([
    
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f59e0b")),
    
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
    
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
    ]))
    
    elements.append(aging_table)
    
    elements.append(PageBreak())
    # =====================================
    # TOP RISK NODES
    # =====================================

    risk_title = Paragraph(

        "<b>Top Risk Nodes</b>",

        styles["Heading2"]
    )

    elements.append(risk_title)

    elements.append(Spacer(1, 10))

    risk_data = [[

        "Circle",
        "Node",
        "Task",
        "Delay"
    ]]

    for item in report["top_risk_nodes"][:10]:

        risk_data.append([

            item["circle"],
            item["node"],
            item["task"],
            f"{item['max_delay']} days"
        ])

    risk_table = Table(
        risk_data,
        repeatRows=1,
        colWidths=[120, 120, 160, 80]
    )

    risk_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dc2626")),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(risk_table)

    elements.append(Spacer(1, 25))
    elements.append(PageBreak())
    # =====================================
    # LEADERSHIP ACTIONS
    # =====================================
    
    leadership_title = Paragraph(
    
        "Leadership Actions",
    
        section_style
    )
    
    elements.append(leadership_title)
    
    elements.append(Spacer(1, 10))
    
    leadership_data = [[
    
        "Priority",
        "Action",
        "Owner",
        "Status",
        "Overdue"
    ]]
    
    for item in report["leadership_actions"]:
    
        leadership_data.append([
    
            item["priority"],
    
            item["action"],
    
            item["owner"],
    
            item["status"],
    
            f"{item['overdue_days']} days"
            if item["overdue_days"] > 0
            else "On Track"
        ])
    
    leadership_table = Table(
    
        leadership_data,
        
        repeatRows=1,
    
        colWidths=[70, 180, 100, 80, 80]
    )
    
    leadership_table.setStyle(TableStyle([
    
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
    
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
    
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
    ]))
    
    elements.append(leadership_table)

    elements.append(Spacer(1, 25))
    
    
    # =====================================
    # BUILD PDF
    # =====================================

    doc.build(

    elements,

    onFirstPage=add_page_footer,

    onLaterPages=add_page_footer
    )

    pdf = buffer.getvalue()

    buffer.close()

    return pdf